### ISSUE TITLE
tree.plot_tree(clf) for ShapeletDecisionTree class

### ISSUE THREAD

**Issue by lorebon** [wildboar-foundation/wildboar#32]
Dear Isak,

I was wondering if it's possible to plot a ShapeletDecisionTree structure like the scikit-learn method. For example:

![output_10_0](https://user-images.githubusercontent.com/95094358/155545304-7417f97e-f7b5-491d-b47e-86f7cb278b27.png)

It would be nice plotting the corresponding shapelet for each split. I don't think it's hard since the ShapeletDecisionTree class it's very similar to the classic one.

Do you have any ideas? Thanks in advance!

**Comment by isaksamsten** [comment]
This should be doable.

**Comment by isaksamsten** [comment]
Hi!

You can plot trees now!

```python
import matplotlib.pyplot as plt
from wildboar.datasets import load_two_lead_ecg
from wildboar.tree import ShapeletTreeClassifier
from wildboar.utils.plot import plot_tree

X_train, X_test, y_train, y_test = load_two_lead_ecg(merge_train_test=False)
clf = ShapeletTreeClassifier(
    n_shapelets=1,
    impurity_equality_tolerance=0.0,
    metric="scaled_euclidean",
    random_state=1,
)
clf.fit(X_train, y_train)
clf.score(X_test, y_test)

fig, ax = plt.subplots(figsize=(10, 6))
plot_tree(clf, ax=ax, show_classes=False)
```

Produces the following image:
![output](https://github.com/wildboar-foundation/wildboar/assets/167128/79bb6bc6-0f55-406f-9d44-90133544d0f1)
