### ISSUE TITLE
will it work for windows ?

### ISSUE THREAD

**Issue by Sandy4321** [wildboar-foundation/wildboar#81]
Universal binaries are compiled for GNU/Linux and Python 3.8, 3.9, 3.10

will it work for windows ?

**Comment by isaksamsten** [comment]
Yes!

We compile binaries for Windows, macOS and GNU/Linux, for Python 3.8, 3.9, 3.10 and 3.11.

**Comment by Sandy4321** [comment]
can it be installed by pip?

**Comment by isaksamsten** [comment]
Yes!

```
pip install wildboar
```

If you want to build from source, follow the instructions in the [documentation](https://wildboar.dev/main/quickstart/install.html#build-and-compile-from-source).
