### ISSUE TITLE
you request  scikit-learn>=1.2rc1,<1.3a0 but pip install -U wildboar installs very old scikit-learn-1.1.3 

### ISSUE THREAD

**Issue by Sandy4321** [wildboar-foundation/wildboar#82]
**Describe the bug**

you request 
scikit-learn>=1.2rc1,<1.3a0
but pip install -U wildboar
installs very old
scikit-learn-1.1.3 

installation fails 
you have requirement 
Cython>=0.29.24
numpy>=1.21.0
scikit-learn>=1.2rc1,<1.3a0
scipy>=1.3.2

Installation error 
Installing collected packages: scikit-learn, wildboar
  Attempting uninstall: scikit-learn
    WARNING: Ignoring invalid distribution -orch (c:\my_py_environments\py310_env_apr2023\lib\site-packages)
    Found existing installation: scikit-learn 1.2.2
    Uninstalling scikit-learn-1.2.2:
      Successfully uninstalled scikit-learn-1.2.2
WARNING: Ignoring invalid distribution -orch (c:\my_py_environments\py310_env_apr2023\lib\site-packages)
WARNING: Ignoring invalid distribution -orch (c:\my_py_environments\py310_env_apr2023\lib\site-packages)
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
pyts 0.13.0 requires scikit-learn>=1.2.0, but you have scikit-learn 1.1.3 which is incompatible.
Successfully installed scikit-learn-1.1.3 wildboar-1.1.1

![image](https://github.com/wildboar-foundation/wildboar/assets/11426119/e2169ef6-4f10-48a8-85ae-b0161d6ce8aa)

**To Reproduce**
pip install -U wildboar

**Expected behavior**

**Setup (please complete the following information):**
 - OS: [e.g. iOS] Windows 11
 - Python version: Python 3.10.11
 - NumPy version: np.__version__
'1.23.5'
 - Cython version:
 - Cython.__version__
'0.29.35'

 - Wildboar version: (version or commit)
 -  wildboar-1.1.1
 - 

**Additional context**

**Comment by isaksamsten** [comment]
For 1.1 I have set the upper bound on scikit learn to 1.2a, to ensure compatibility. I’m in the process of releasing 1.2 which will use a more modern scikit learn version.

You can build from source on the 1.1.X branch (or the 1.1.1 tag) and change the requirement in pyproject.toml to resolve the error, but it’s not guaranteed that everything works since scikit learn might have made some breaking change in 1.2 that I depend on.

**Comment by isaksamsten** [comment]
You would also have to pin the dependency on Cython to 0.29

**Comment by isaksamsten** [comment]
This issue has been fixed in 1.1.2 (and master).

You can install the latest version with: `pip install wildboar==1.1.2`

**Comment by Sandy4321** [comment]
thanks
