### ISSUE TITLE
_check_estimator_name no longer included in sklearn.utils.validation

### ISSUE THREAD

**Issue by lorebon** [wildboar-foundation/wildboar#92]
Hi Isak,

"from sklearn.utils.validation import (
    _check_estimator_name,
    _check_y,
    check_consistent_length,
    warnings,
)"

This import is no longer working with the most recent version of scikit-learn.

The same is happening with '_fit_context' from 'sklearn.base'. Any suggestions? Thank you!

**Comment by lorebon** [comment]
I think the first one is now in sklearn.utils.estimato_checks under the name of "check_estimator".

The second one must be now "check_X_y"

**Comment by isaksamsten** [comment]
Hi!
what version are you using?

**Comment by lorebon** [comment]
I'm using the latest one, wildboar 1.2

**Comment by isaksamsten** [comment]
1.1 requires scikit-learn <1.4. The currently unreleased 1.2 requires scikit-learn >=1.3

**Comment by isaksamsten** [comment]
Could you give me the version of scikit-learn. It should work for 1.3 and later

**Comment by lorebon** [comment]
Ok I updated scikit-learn to 14.0, but now I'm facing this error:

"requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='datasets.wildboar.dev', port=443): Read timed out. (read timeout=3)"

**Comment by isaksamsten** [comment]
I recently reduced the timeout and "it was working fine on my machine"... I will need to increase this.

I think you can do:

```python
from wildboar.datasets import refresh_repositories
refresh_repositories(timeout=30)
```

before your call to `load_dataset` (or which ever function you used)

**Comment by lorebon** [comment]
OK, now it perfectly runs, thank you!

**Comment by isaksamsten** [comment]
Could you tell me if you were using scikit learn 1.2 or 1.3 when you got the initial error? I want to ensure that it works with both and I think it should but I could be mistaken

**Comment by lorebon** [comment]
When I read your answer I immediately updated, I'm not sure but I think it was the 1.2

**Comment by lorebon** [comment]
Is there a way to check the version history of installed packages?

**Comment by isaksamsten** [comment]
I don’t think so. I will test and see if I can reproduce with 1.3 otherwise I think you were using an older version.
